### ISSUE TITLE
segfault on TCP mode after set clients number on some value

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [Sinodun/dnsperf-tcp#5]
I am trying to use dnsperf (build on Fedora 24) against [CoreDNS](https://github.com/coredns/coredns) to figure out how many connection it can open.
File dnsperf.c has line
`#define MAX_SOCKETS 256`
so I changed it with
`#define MAX_SOCKETS 2048`
Observed that command
`dnsperf -s 127.0.0.1 -p 53 -d dns.txt -Q 10000 -l 10 -z -c 1077`
works fine but command
`dnsperf -s 127.0.0.1 -p 53 -d dns.txt -Q 10000 -l 10 -z -c 1078`
failed with message "Segmentation fault".

**Comment by saradickinson** [comment]
I'll take a look...  don't suppose you have the core dump?

If it is a limitation within dnsperf then you could try running multiple instances of dnsperf to create the total number of connections you want to test.

**Comment by UladzimirTrehubenka** [comment]
`gcc -fstack-protector-all` shows that we have stack corruption in `perf_os_waituntilanyreadable`.

**Comment by UladzimirTrehubenka** [comment]
Found root of the issue - see https://github.com/FreeRADIUS/pam_radius/issues/24
Need replace `select` with `poll`.

**Comment by saradickinson** [comment]
Looks like that could be it - thanks for tracking this down! I guess the original implementation didn't expect to need that many fds...
I'll try to get a fix done in the next couple of days.

**Comment by saradickinson** [comment]
I've created https://github.com/Sinodun/dnsperf-tcp/pull/8 which I think should solve the problem. Feel free to test.
